### ISSUE TITLE
Hooks to change the color of the debug grid?

### ISSUE THREAD

**Issue by hrdlnk** [u-fischer/returntogrid#2]
Is there a hook available to change the color of the debug grid? I fiddled a bit with tikz incantations but still no luck.

If not, make that a feature request

Thanks for this awesome package. It seems to play well with the Tufte-LaTeX class so far :)

**Comment by u-fischer** [comment]
Well it is only a simple debug grid. Sophisticated design wasn't planed here. But I made the color configurable. Get the new sty in the source folder and then use 

~~~~
\colorlet{ufgrid@debugcolor}{blue}

~~~~
